name: Licensed

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  licensed:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

    - name: Install dependencies
      run: npm install --production

    - name: Set up licensed
      uses: jonabc/setup-licensed@d6b3a6f7058c2b40c06d205e13e15c2418977566 # v1.1.4
      with:
        version: '2.x'

    - name: List licenses
      run: licensed list

    - name: Check license status
      run: licensed status
