name: Licensed

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  licensed:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install --production

    - name: Set up licensed
      uses: jonabc/setup-licensed@v1
      with:
        version: '2.x'

    - name: List licenses
      run: licensed list

    - name: Check license status
      run: licensed status
