name: Validate
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: 0 0 * * *

jobs:
  local-cache:
    name: Setup local-cache version
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        tor: [0.4.5-rc7, 0.4.5.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate setup-tor ${{ matrix.tor }}
        uses: ./
        with:
          tor-version: ${{ matrix.tor }}

      - name: Verify tor
        run: __tests__/verify-tor.sh ${{ matrix.tor }}
        shell: bash

  setup-versions-from-manifest:
    name: Setup ${{ matrix.tor }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        tor: [0.4.5-rc7, 0.4.5.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Validate setup-tor ${{ matrix.tor }}
        uses: ./
        with:
          tor-version: ${{ matrix.tor }}
      
      - name: Verify tor
        run: __tests__/verify-tor.sh ${{ matrix.tor }}
        shell: bash

  setup-default-version:
    name: Setup Tor as default version on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Validate setup-tor
        uses: ./
      
      - name: Verify tor
        run: __tests__/verify-tor.sh 'emit'
        shell: bash

  setup-with-daemon:
    name: Setup Tor with daemon
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate setup-tor
        uses: ./
        with:
          daemon: true

      - name: Verify tor
        run: |
          ps -aux | grep bin | grep tor || { echo 'Run Tor failed' 1>&2; exit 1; }
          netstat -anp | grep :9050
          lsof | grep 9050
        shell: bash

      - name: Validate setup-tor
        uses: ./
        with:
          daemon: true
          port: 12345

      - name: Verify tor
        run: |
          ps -aux | grep bin | grep tor || { echo 'Run Tor failed' 1>&2; exit 1; }
          netstat -anp | grep :12345
          lsof | grep 12345
        shell: bash
